sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t leofofeo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true leofofeo/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-course"
    env: "DockerCourse-env"
    bucket_name: "elasticbeanstalk-us-east-2-094067287546"
    bucket_path: "docker-course"
    on:
        branch: master
    # access key and secret key are stored in travis
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"


